### PR TITLE
LRDOCS-2426 Item Selector API tutorials

### PR DESCRIPTION
**Pull request by mwilliams2014**
@robertoDiaz Hi, can you review these tutorials and intro for accuracy? I've added some questions as comments to the tutorials that I have as well.

thx!

### CODE REVIEW

**Comment by mwilliams2014** [comment]
Closing this and reassigning to @adolfopa for review

**Comment by mwilliams2014** [comment]
@robertoDiaz opening the pr back to you. thx!

**Comment by mwilliams2014** [comment]
@robertoDiaz Updated tutorials. Can you please review these as the SME. I've also added some commented questions for your feedback. Please let me know what your thoughts are on them.
thx!

Mike

**Comment by robertoDiaz** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by robertoDiaz** [comment]
Pull request submitted to https://github.com/mwilliams2014/liferay-docs/pull/76. [See changes here.](https://github.com/robertoDiaz/liferay-docs/compare/43dde28~1...43dde28) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request closed without merging**
